console.log("linked page works");

var products = [
  {
    name: "Ultra Slut Body Detergent",
    category: "other",
    price: "$5.99",
    picture: "https://s-media-cache-ak0.pinimg.com/236x/27/a8/5d/27a85d53a7aa13fd5ee21c5b8d4b8405.jpg",
    sellingPoints: ["get rid of the nastyiest oders", "good for hard to reach places", "dirt cheap"],
  },
  {
    name: "Thongies: Super Mega Fierce Diapers",
    category: "wearables",
    price: "14.99",
    picture: "https://s-media-cache-ak0.pinimg.com/736x/54/ee/73/54ee73e58e59447896fc09825e62433f.jpg",
    sellingPoints: ["less materials means less cost", "nice snug fit", "it's inevitable anyway"],
  },
  {
    name: "Shag The Pony And Other Stories",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/17/enhanced/webdr11/edit-32603-1416003134-29.jpg",
    sellingPoints: [],
  },
  {
    name: "Still Stripping After 25 Years",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/15/enhanced/webdr05/enhanced-28729-1415996770-18.jpg",
    sellingPoints: [],
  },
  {
    name: "Who Will Toss My Salad?",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/15/enhanced/webdr11/enhanced-20743-1415996771-21.jpg",
    sellingPoints: ["a little golden book"],
  },
  {
    name: "A Passion For Donkeys",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/17/enhanced/webdr11/edit-14060-1416004767-13.jpg",
    sellingPoints: [],
  },
  {
    name: "The Best Dad Is A Good Lover ",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/15/enhanced/webdr10/enhanced-18723-1415996769-8.jpg",
    sellingPoints: [],
  },  
  {
    name: "The Muffin Muncher",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/15/enhanced/webdr11/enhanced-20681-1415996773-11.jpg",
    sellingPoints: [],
  },  
  {
    name: "Drummer Dick's Discharge",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/16/enhanced/webdr09/enhanced-10544-1416000739-19.jpg",
    sellingPoints: [],
  },
  {
    name: "Scouts In Bondage",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/17/enhanced/webdr07/enhanced-21332-1416002747-16.jpg",
    sellingPoints: [],
  },
  {
    name: "Old Tractors And The Men Who Love Them",
    category: "book",
    price: "",
    picture: "https://img.buzzfeed.com/buzzfeed-static/static/2014-11/14/15/enhanced/webdr08/enhanced-22299-1415996769-18.jpg",
    sellingPoints: ["how to keep your tracktors happy and your family running"],
  },
  {
    name: "Everything I Want To Do Is Illegal ",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-23.jpg",
    sellingPoints: [],
  },
  {
    name: "Mommy Drinks Because You're Bad",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-21.jpg",
    sellingPoints: ["quality religious books for children"],
  },
  {
    name: "Make Your Own Sex Toys",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-20.jpg",
    sellingPoints: ["a practical guide to a better love life", "50 quick and easy projects", "with step-by-step pictures"],
  },
  {
    name: "Are Women Human? ",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-13.jpg",
    sellingPoints: [],
  },
  {
    name: "Who Cares About Elderly People?",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-10.jpg",
    sellingPoints: ["who cares."],
  },
  {
    name: "The Big Book Of Lesbian Horse Stories",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-06.jpg",
    sellingPoints: ["when these Sapphic sisters saddle up, ecstasy is only a hoofbeat away!"],
  },
  {
    name: "Everything I Know About Women I Learned From My Tractor",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-05.jpg",
    sellingPoints: ["a real ladies man"],
  },
  {
    name: "Does God Ever Speak Through Cats?",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-07.jpg",
    sellingPoints: ["I sure hope so"],
  },
  {
    name: "How To Raise Your I.Q. By Eating Gifted Children",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-08.jpg",
    sellingPoints: [],
  },
  {
    name: "Invisible Dick",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-03.jpg",
    sellingPoints: [],
  },
  {
    name: "I Could Pee On This",
    category: "book",
    price: "",
    picture: "http://ecx.images-amazon.com/images/I/51axz2dw8pL.jpg",
    sellingPoints: ["and other poems by cats"],
  },
  {
    name: "Why Cats Paint",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-30.jpg",
    sellingPoints: [],
  },
  {
    name: "Fancy Coffins: To Make Yourself",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-29.jpg",
    sellingPoints: [],
  },
  {
    name: "What's Your Poo Telling You?",
    category: "book",
    price: "",
    picture: "http://www.seenox.org/wp-content/uploads/2014/03/Funny-Worst-Book-Titles-And-Covers-28.jpg",
    sellingPoints: [],
  },
  {
    name: "Toe Tunes Slipper Speakers",
    category: "wearables",
    price: "",
    picture: "http://news.nster.com/images/uploaded/00/01/16/11697_700x.jpg",
    sellingPoints: ["The ultimate toe jam!", "extra bonus: turn your slippers into headphones with the included headband"],
  },
  {
    name: "Soup For Sluts",
    category: "food",
    price: "",
    picture: "http://justsomething.co/wp-content/uploads/2014/05/product-name-fail-6.jpg",
    sellingPoints: ["cheap & easy just like you, you slut"],
  },
  {
    name: "American Sunglasses",
    category: "wearables",
    price: "",
    picture: "https://henkedesign.files.wordpress.com/2012/11/usa-american-sunglasses.jpeg",
    sellingPoints: [],
  },
  {
    name: "Camel Balls Bubble Gum",
    category: "food",
    price: "",
    picture: "http://assets.rebelcircus.com/blog/wp-content/uploads/2016/03/badproducts.jpg",
    sellingPoints: ["Extra sour bubble gum", "liquid filled"],
  },
  {
    name: "Visorganizer",
    category: "wearables",
    price: "",
    picture: "https://img.apmcdn.org/656eb80c537fb8f4554be63df13c0a5c8802aedb/uncropped/f9d494-20071210-visor.jpg",
    sellingPoints: ["use your head and stay organized", "carry up to 7 lbs", "weather-proof material", "4 handy storage areas", "adjustable clips make mounting a snap"],
  },
  {
    name: "Crib Dribbler",
    category: "food",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/564x/cd/8f/cf/cd8fcfd6f2072224bd63c833cb8eb891.jpg",
    sellingPoints: ["feeding system", "saves time for more important things"],
  },
  {
    name: "Bathe & Brew",
    category: "food",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/564x/f8/52/bb/f852bbc3c338680021bd5d6c16ab55c1.jpg",
    sellingPoints: ["shower coffee maker and soap dispenser"],
  },
  {
    name: "Connect A Cord",
    category: "other",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/736x/1e/c4/c2/1ec4c2254ede03b8449955fcf7678bbc.jpg",
    sellingPoints: ["the perfect length cord everytime", "up to 50feet!"],
  },
  {
    name: "Bacon Scented Sizzl Dryer Sheets",
    category: "other",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/736x/09/68/0b/09680bd5d68009da8fecd4583ec28c3f.jpg",
    sellingPoints: ["wall despenser included", "breakfast fresh scent"],
  },
  {
    name: "iArm Forearm Mount",
    category: "wearables",
    price: "",
    picture: "http://images.fastcompany.com/upload/iArmBIG.jpg",
    sellingPoints: ["compatible with ipad, kindle, remotes, dishplates, and more!"],
  },
  {
    name: "Froogal Glass Wearable & Disposable Camera",
    category: "wearables",
    price: "",
    picture: "http://cdn.shopify.com/s/files/1/0336/6705/products/PP.3DHeros.Froogal.RightFace.HR.Batch2_1024x1024.png?v=1449070796",
    sellingPoints: ["your life captured", "1/16 the cost of other wearables"],
  },
  {
    name: "Earwax Candle Kit",
    category: "other",
    price: "",
    picture: "http://cdn.shopify.com/s/files/1/0336/6705/products/PP.3DHeros.Earwax.RightFace.HR.Batch1.png_copy_1024x1024.jpg?v=1448390823",
    sellingPoints: ["create a candle as unique as yourself", "wax extraction cap included"],
  },
  {
    name: "Coffee Talkies",
    category: "food",
    price: "",
    picture: "http://images.fastcompany.com/upload/CoffeeTalkies.jpg",
    sellingPoints: ["the original travel mug / 2-way radio", "1200 foot range"],
  },
  {
    name: "Pet Petter",
    category: "other",
    price: "",
    picture: "http://1.bp.blogspot.com/-ZoK_rtghj88/TtguyeKS7pI/AAAAAAAAFhk/MdJDQdWEJcg/s1600/HR.WebAddress.PetPetter.HR_.Back_.jpg",
    sellingPoints: ["never touch your pets again", "up to 85ppm (pets per minute)", "versatile attachements sold separately"],
  },
  {
    name: "Beer Beard Secret Beverage Dispenser",
    category: "wearables",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/736x/8e/6f/e1/8e6fe14ceb32335d945f686b06432e99.jpg",
    sellingPoints: ["cleverly hide 72oz. of beer", "the great outdoors just got greater!"],
  },
  {
    name: "Extreme Motion Controlled Video Game Chores",
    category: "other",
    price: "",
    picture: "http://i.imgur.com/MbKWj.png",
    sellingPoints: ["yard work", "dishes", "raking", "litterbox"],
  },
  {
    name: "Robocroc",
    category: "movie",
    price: "movie",
    picture: "http://whatav.whatgroupmag.com/wp-content/uploads/2015/04/Robocroc-Terror-Bi%C3%B4nico.jpg",
    sellingPoints: ["the world's most lethal weapon"],
  },
  {
    name: "Sharktopus Vs Whalewolf",
    category: "movie",
    price: "",
    picture: "http://kdvd.in/wp-content/uploads/2016/07/948-Sharktopus-vs-Whalewolf-2015.jpg",
    sellingPoints: ["when a mad scientist mixes the genes of a killer whale and a wolf, it creates the whalewolf, and it's up to sharktopus to stop it."],
  },
  {
    name: "Three Headed Shark Attack",
    category: "movie",
    price: "",
    picture: "https://s29.postimg.io/d5qabje07/Tkpcd_NOVi.jpg",
    sellingPoints: ["uncut", "Danny Trejo"],
  },
  {
    name: "Yeti Curse Of The Snow Demon",
    category: "movie",
    price: "",
    picture: "http://recours.r.e.pic.centerblog.net/dx7v2ro0.jpg",
    sellingPoints: ["surviving the crash was only the beginning", "it kills in cold blood"],
  },
  {
    name: "Lavalantula",
    category: "movie",
    price: "",
    picture: "http://upload.aflamhq.com/14571353197045_AflamHQ.com.jpg",
    sellingPoints: ["fire burns lava bites"],
  },
  {
    name: "Sharknado",
    category: "movie",
    price: "",
    picture: "http://hellnotes.com/wp-content/uploads/2013/09/sharknado-dvd.jpg",
    sellingPoints: ["enough said!", "when a freak hurricane swamps Los Angeles, thousands of sharks terrorize the waterlogged populous.  And when the high-speed winds from tornadoes in the desert, nature's dealiest killer rules water, land, and air."],
  },
  {
    name: "Machete",
    category: "movie",
    price: "",
    picture: "http://covers.box.sk/newsimg/dvdmov/max1300491004-frontback-cover.jpg",
    sellingPoints: ["Danny Trejo", "Michelle Rodriguez", "Robert De Niro", "Steven Seagal", "Jessica Alba"],
  },
  {
    name: "Planet Terror",
    category: "movie",
    price: "",
    picture: "http://www.dvd-covers.org/d/97263-3/PLANET_TERROR.jpg",
    sellingPoints: ["an instant classic"],
  },
  {
    name: "HK: Panty-Man! Forbidden Superhero",
    category: "movie",
    price: "",
    picture: "http://img.photobucket.com/albums/v203/yanie/news_large_HK_poster_zpsd733ec84.jpg",
    sellingPoints: [],
  },
  {
    name: "Troll 2",
    category: "movie",
    price: "",
    picture: "http://covers.box.sk/newsimg/dvdmov/max1303844248-frontback-cover.jpg",
    sellingPoints: ["be afraid...", "be twice as afraid!"],
  },
  {
    name: "Fetal Mice Donut",
    category: "food",
    price: "",
    picture: "https://s-media-cache-ak0.pinimg.com/736x/1c/e2/94/1ce2946187fa9de423490a4d49d6e418.jpg",
    sellingPoints: ["delicious", "high in protein", "kinda crunchy"],
  },
  {
    name: "A Bowl Of Rotting Fruit",
    category: "",
    price: "",
    picture: "http://media.gettyimages.com/videos/fruit-bowl-rotting-video-id142306070?s=640x640",
    sellingPoints: ["alcoholic", "already partially digested for you"],
  },




  ];



/*



  {
    name: "",
    category: "",
    price: "",
    picture: "",
    sellingPoints: [],
  },

*/

